.TH LIBMEMS 3
.SH libmems
libmems - Serial interface library for Rover MEMS engine management computer

.SH SYNOPSIS
.B #include <mems.h>

.SH NOTES
The MEMS ECU does not use standard RS-232 signaling characteristics, instead using 5V TTL levels. This library therefore requires a serial adapter capable of 0-5VDC levels. Strongly recommended is the FTDI TTL-232R-5V. See the
.B RESOURCES
section for more information.

.SH DESCRIPTION
This library provides an interface to the diagnostic serial port on the Rover MEMS engine management computer.

.SH EXAMPLE
mems_info info;
.br
mems_init(&info);
.br
.nf
if (mems_connect(&info, "/dev/ttyUSB0"))
{
    mems_data params;
    bool readSuccess = mems_read(&info, &params);
}
.br
mems_cleanup(&info);

.SH RESOURCES
Information about building a compatible serial cable is available in the Wiki section of the project's Google Code web site:
.br
.I http://code.google.com/p/libmems/

.SH AUTHOR
Colin Bourassa <colin.bourassa@gmail.com>
